services:
  postgres:
    image: postgres:17
    container_name: adh-franconia-db
    environment:
      POSTGRES_DB: adh_franconia
      POSTGRES_USER: franconia
      POSTGRES_PASSWORD: franconia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: