spring.application.name=adh-franconia

spring.datasource.url=jdbc:postgresql://localhost:5433/adh_franconia
spring.datasource.username=franconia
spring.datasource.password=franconia

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080


app.frontend-origin=http://localhost:4200


security.jwt.issuer=https://adh.franconia-tuebingen.de

security.jwt.audience=adh-api

security.jwt.access-token-lifetime=15m

security.jwt.refresh-token-lifetime=30d

security.refresh-cookie-secure=false

security.jwt.private-key=file:${JWT_PRIVATE_KEY}
security.jwt.public-key=file:${JWT_PUBLIC_KEY}