spring.application.name=adh-franconia

spring.datasource.url=jdbc:postgresql://localhost:5433/adh_franconia
spring.datasource.username=franconia
spring.datasource.password=franconia

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
server.port=8080